src/main/java/cz/uhk/ppro/form/AddWordForm.java
package cz.uhk.ppro.form;

public class AddWordForm {
    private String word1;
    private String word2;

    public String getWord1() {
        return word1;
    }

    public void setWord1(String word1) {
        this.word1 = word1;
    }

    public String getWord2() {
        return word2;
    }

    public void setWord2(String word2) {
        this.word2 = word2;
    }
}

src/main/java/cz/uhk/ppro/form/LoginForm.java
package cz.uhk.ppro.form;

public class LoginForm {

    private String email;

    private String password;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

src/main/java/cz/uhk/ppro/form/RegisterForm.java
package cz.uhk.ppro.form;

public class RegisterForm extends LoginForm {

    private String confirmPassword;

    private String name;

    private String surname;

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }

    public String getSurname() { return surname; }

    public void setSurname(String surname) { this.surname = surname; }

    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

}

src/main/java/cz/uhk/ppro/model/PracticeWord.java
package cz.uhk.ppro.model;

import cz.uhk.ppro.entities.Word;

public class PracticeWord {

    private Word wordForTranslation;

    private Word wordTranslated;

    private Integer correctCount;

    private Integer wrongCount;

    public PracticeWord(Word wordForTranslation, Word wordTranslated) {
        this.wordForTranslation = wordForTranslation;
        this.wordTranslated = wordTranslated;
        this.correctCount = 0;
        this.wrongCount = 0;
    }

    public Integer getScore() {
        return -wrongCount + correctCount;
    }

    public Integer getCorrectCount() {
        return correctCount;
    }

    public void setCorrectCount(Integer correctCount) {
        this.correctCount = correctCount;
    }

    public Integer getWrongCount() {
        return wrongCount;
    }

    public void setWrongCount(Integer wrongCount) {
        this.wrongCount = wrongCount;
    }

    public Word getWordForTranslation() {
        return wordForTranslation;
    }

    public void setWordForTranslation(Word wordForTranslation) {
        this.wordForTranslation = wordForTranslation;
    }

    public Word getWordTranslated() {
        return wordTranslated;
    }

    public void setWordTranslated(Word wordTranslated) {
        this.wordTranslated = wordTranslated;
    }

    public void incrementCorrectCount() {
        correctCount++;
    }

    public void incrementWrongCount() {
        wrongCount++;
    }

}

src/main/java/cz/uhk/ppro/controllers/AllListsController.java
package cz.uhk.ppro.controllers;

import cz.uhk.ppro.entities.WordList;
import cz.uhk.ppro.service.VocabularyServiceImpl;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.LinkedList;
import java.util.List;

@Controller
@RequestMapping("/allLists")
public class AllListsController {

    private final VocabularyServiceImpl vocabularyService;

    public AllListsController(VocabularyServiceImpl vocabularyService) {
        this.vocabularyService = vocabularyService;
    }

    @RequestMapping(value = "", method = RequestMethod.GET)
    public ModelAndView allLists(Model model, HttpServletRequest request, HttpSession session){

        List<WordList> wlList = vocabularyService.findWordLists();
        LinkedList<WordList> linkedWL = new LinkedList<WordList>();
        linkedWL.addAll(wlList);
        ModelAndView mapWL = new ModelAndView("allLists");
        mapWL.addObject("lists", linkedWL);

        return mapWL;
    }

}

src/main/java/cz/uhk/ppro/controllers/CreateController.java
package cz.uhk.ppro.controllers;

import cz.uhk.ppro.entities.Language;
import cz.uhk.ppro.entities.Word;
import cz.uhk.ppro.entities.WordList;
import cz.uhk.ppro.form.AddWordForm;
import cz.uhk.ppro.form.WordListForm;
import cz.uhk.ppro.model.PracticeWord;
import org.springframework.ui.Model;
import cz.uhk.ppro.service.VocabularyServiceImpl;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.view.RedirectView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import java.util.LinkedList;
import java.util.List;

@Controller
public class CreateController {

    private final VocabularyServiceImpl vocabularyService;

    public CreateController(VocabularyServiceImpl vocabularyService) {
        this.vocabularyService = vocabularyService;
    }

    @InitBinder("wordListForm")
    public void initWordListBinder(WebDataBinder dataBinder) {
        dataBinder.setValidator(new CreateWordListFormValidator());
    }

    @InitBinder("addWordForm")
    public void initWordBinder(WebDataBinder dataBinder) {
        dataBinder.setValidator(new AddWordFormValidator());
    }

    @RequestMapping(value = "create", method = RequestMethod.GET)
    public String create(Model model) {

        List<Language> ll = vocabularyService.findLanguages();
        LinkedList<Language> langList = new LinkedList<Language>();
        langList.addAll(ll);
        model.addAttribute("languages", langList);
        return "create";
    }

    @RequestMapping(value = "create", method = RequestMethod.POST)
    public String createProcess(Model model, @Valid WordListForm wordListForm, BindingResult result) {
        if(result.hasErrors()){
            result.reject("msg", "Wrong input.");
            return create(model);
        } else {
            WordList wl = new WordList(wordListForm.getName(), wordListForm.getDescription(), wordListForm.getIso1(), wordListForm.getIso2());
            vocabularyService.saveOrUpdateWL(wl);
            return "redirect:/addWords/" + Integer.toString(wl.getId());
        }
    }

    private Word findWord(Word word, final String language) {
        if (word.getLanguage().equals(language)) return word;
        for (Word wordTranslation : word.getTranslations()) {
            if (wordTranslation.getLanguage().equals(language)) {
                return wordTranslation;
            }
        }
        return null;
    }

    @RequestMapping(value = "/addWords/{wordListId}", method = RequestMethod.GET)
    public String addWords(@PathVariable("wordListId") int wordListId, Model model) {
        WordList wl = vocabularyService.findWordListById(wordListId);
        model.addAttribute("list", wl);

        LinkedList<PracticeWord> wordsLinkedList = new LinkedList<PracticeWord>();
        for (Word word : wl.getWords()) {
            Word wordForTranslation = findWord(word, wl.getLang1());
            Word wordTranslated = findWord(word, wl.getLang2());
            if (wordForTranslation != null && wordTranslated != null) {
                wordsLinkedList.add(new PracticeWord(wordForTranslation, wordTranslated));
            }
        }
        model.addAttribute("words", wordsLinkedList);

        return "addWords";
    }

    @RequestMapping(value = "/addWords/{wordListId}", method = RequestMethod.POST)
    public String addWordsProcess(Model model, @Valid AddWordForm addWordForm, BindingResult result, @PathVariable("wordListId") int wordListId) {
        if (result.hasErrors()) {
            result.reject("msg", "Wrong input.");
        } else {
            WordList wl = vocabularyService.findWordListById(wordListId);
            Word wd1 = new Word(addWordForm.getWord1());
            Word wd2 = new Word(addWordForm.getWord2());
            wd1.setLanguage(wl.getLang1());
            wd2.setLanguage(wl.getLang2());

            vocabularyService.saveNewWords(wd1, wd2, wl);
        }

        return addWords(wordListId, model);
    }

}

src/main/java/cz/uhk/ppro/controllers/HomeController.java
package cz.uhk.ppro.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpSession;

@Controller
@RequestMapping("/")
public class HomeController {

    @RequestMapping(method = RequestMethod.GET)
    public String home(Model model, HttpSession session) {
        if (session.getAttribute("Email") != null) {
            return "redirect:/lists";
        } else {
            return "redirect:/login";
        }
    }

}

src/main/java/cz/uhk/ppro/controllers/ListsController.java
package cz.uhk.ppro.controllers;

import cz.uhk.ppro.entities.User;
import cz.uhk.ppro.entities.WordList;
import cz.uhk.ppro.service.VocabularyServiceImpl;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.Arrays;
import java.util.Comparator;
import java.util.LinkedList;


@Controller
public class ListsController {

    private final VocabularyServiceImpl vocabularyService;

    public ListsController(VocabularyServiceImpl vocabularyService) {
        this.vocabularyService = vocabularyService;
    }

    @RequestMapping(value = "lists", method = RequestMethod.GET)
    public ModelAndView lists(Model model, HttpServletRequest request, HttpSession session){

        String usersEmail = (String) session.getAttribute("Email");
        User user = vocabularyService.findUserByEmail(usersEmail);
        LinkedList<WordList> usersWL = new LinkedList<WordList>();
        usersWL.addAll(user.getWordLists());
        WordList[] usersWLsArray = (WordList[]) usersWL.toArray(new WordList[usersWL.size()]);
        Arrays.sort(usersWLsArray, new SortByName());
        ModelAndView mapWL = new ModelAndView("lists");
        mapWL.addObject("users", usersWLsArray);

        return mapWL;
    }

    @RequestMapping(value = "lists/add/{wordListId}", method = RequestMethod.GET)
    public ModelAndView add(Model model, HttpServletRequest request, HttpSession session, @PathVariable("wordListId") int wordListId) {
        String usersEmail = (String) session.getAttribute("Email");
        User user = vocabularyService.findUserByEmail(usersEmail);
        WordList list = vocabularyService.findWordListById(wordListId);
        user.addList(list);
        vocabularyService.saveOrUpdateUser(user);
        return lists(model, request, session);
    }
}

class SortByName implements Comparator<WordList> {
    public int compare(WordList a, WordList b)  {
        return a.getName().compareTo(b.getName());
    }
}

src/main/java/cz/uhk/ppro/controllers/LoginController.java
package cz.uhk.ppro.controllers;

import cz.uhk.ppro.entities.User;
import cz.uhk.ppro.form.LoginForm;
import cz.uhk.ppro.form.RegisterForm;
import cz.uhk.ppro.service.VocabularyServiceImpl;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.List;

@Controller
@RequestMapping("/login")
public class LoginController {

    private final VocabularyServiceImpl vocabularyService;

    public LoginController(VocabularyServiceImpl vocabularyService) {
        this.vocabularyService = vocabularyService;
    }

    @RequestMapping(method = RequestMethod.GET)
    public String login(Model model, HttpSession session) {
        RegisterForm form = new RegisterForm();
        model.addAttribute("registerForm", form);
        return "login";
    }

    @RequestMapping(method = RequestMethod.POST)
    public String loginProcess(@ModelAttribute("loginForm") LoginForm loginForm, BindingResult result, HttpServletRequest request, HttpSession session) {
        if (areCredentialsCorrect(loginForm.getEmail(), loginForm.getPassword())) {
            String mail = loginForm.getEmail();
            session.invalidate();
            HttpSession newSession = request.getSession();
            newSession.setAttribute("Email", mail);

            return "redirect:/";
        } else {
            result.reject("msg", "Wrong credentials.");
            return "login";
        }
    }

    private boolean areCredentialsCorrect(String email, String password) {
        User userFromDB = vocabularyService.findUserByEmail(email);
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        return userFromDB != null && encoder.matches(password, userFromDB.getPassword());
    }

}

src/main/java/cz/uhk/ppro/controllers/RegisterController.java
package cz.uhk.ppro.controllers;

import cz.uhk.ppro.entities.User;
import cz.uhk.ppro.form.RegisterForm;
import cz.uhk.ppro.service.VocabularyServiceImpl;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;

@Controller
@RequestMapping("/")
public class RegisterController {

    private final VocabularyServiceImpl vocabularyService;

    public RegisterController(VocabularyServiceImpl vocabularyService) {
        this.vocabularyService = vocabularyService;
    }

    @InitBinder("registerForm")
    public void initRegisterFormBinder(WebDataBinder dataBinder) {
        dataBinder.setValidator(new RegisterFormValidator());
    }

    @RequestMapping(value = "/register", method = RequestMethod.GET)
    public String register() {
        return "register";
    }

    @RequestMapping(value = "/register", method = RequestMethod.POST)
    public String registerProcess(@Valid RegisterForm registerForm, BindingResult result, HttpServletRequest request, HttpSession session) {
        if (vocabularyService.findUserByEmail(registerForm.getEmail()) != null) {
            result.reject("msg", "User already exists.");
            return "register";
        }

        if (!result.hasErrors()) {
            String mail = registerForm.getEmail();
            session.invalidate();
            HttpSession newSession = request.getSession();
            newSession.setAttribute("Email", mail);

            // Create user in DB
            BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
            String encodedPassword = encoder.encode(registerForm.getPassword());
            User user = new User(registerForm.getEmail(), encodedPassword, registerForm.getName(), registerForm.getSurname());
            vocabularyService.saveOrUpdateUser(user);

            return "redirect:/";
        } else {
            result.reject("msg", "Wrong input.");
            return "register";
        }
    }

}

src/main/java/cz/uhk/ppro/controllers/StatisticsController.java
package cz.uhk.ppro.controllers;

import cz.uhk.ppro.entities.PracticeDay;
import cz.uhk.ppro.entities.User;
import cz.uhk.ppro.model.PracticeWord;
import cz.uhk.ppro.service.VocabularyServiceImpl;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpSession;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Set;

@Controller
public class StatisticsController {

    private VocabularyServiceImpl vocabularyService;

    public StatisticsController(VocabularyServiceImpl vocabularyService) {
        this.vocabularyService = vocabularyService;
    }

    @RequestMapping(value = "statistics")
    public String statistics(Model model, HttpSession session) {
        String userEmail = (String) session.getAttribute("Email");
        User loggedUser = vocabularyService.findUserByEmail(userEmail);

        Set<PracticeDay> practiceDays = loggedUser.getPracticeDays();
        PracticeDay practiceDaysArray[] = (PracticeDay[]) practiceDays.toArray(new PracticeDay[practiceDays.size()]);
        Arrays.sort(practiceDaysArray, new SortByDate());
        model.addAttribute("practiceDays", practiceDaysArray);

        return "statistics";
    }

}

class SortByDate implements Comparator<PracticeDay> {
    public int compare(PracticeDay a, PracticeDay b)  {
        return -(a.getPracticeDayPK().getDate().compareTo(b.getPracticeDayPK().getDate()));
    }
}

src/main/webapp/WEB-INF/views/addWords.jsp
<%--
  Created by IntelliJ IDEA.
  User: Honza
  Date: 07.01.2020
  Time: 17:05
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page session="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="vocabulary" tagdir="/WEB-INF/tags" %>


<vocabulary:layout pageName="fillWordList">

    <div class="container">
        <h2>Fill the word list: ${list.name}</h2>

        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>${list.lang1}</th>
                    <th>${list.lang2}</th>
                </tr>
                <form:form id="fill-form" modelAttribute="addWordForm" action="/addWords/${list.id}" method="post" role="form">
                <tr>
                    <td>
                        <input autocomplete="off" type="text" name="word1" id="word1" class="form-control">
                    </td>
                    <td>
                        <input autocomplete="off" type="text" name="word2" id="word2" class="form-control">
                    </td>
                </tr>

                <c:set var="formHasRegisterError">
                    <form:errors/>
                </c:set>
                <c:if test="${not empty formHasRegisterError}">
                    <tr>
                        <td colspan="2">
                            <div class="alert alert-danger">
                                <i class="fa fa-ban"></i>&nbsp;${formHasRegisterError}
                            </div>
                        </td>
                    </tr>
                </c:if>

                <tr>
                    <td>
                        <button type="submit" class="btn btn-default">Add word</button>
                    </td>
                    </form:form>
                    <td>
                        <a href="/allLists" class="btn btn-default">Finish</a>
                    </td>
                </tr>
                <tr>
                    <th>Words already in the list:</th>
                    <td></td>
                </tr>
                <c:forEach items="${words}" var="words">
                    <tr>
                        <td>${words.wordForTranslation.spelling}</td>
                        <td>${words.wordTranslated.spelling}</td>
                    </tr>
                </c:forEach>
            </tbody>
        </table>



    </div>

</vocabulary:layout>

src/main/webapp/WEB-INF/views/allLists.jsp
<%--
  Created by IntelliJ IDEA.
  User: Honza
  Date: 06.01.2020
  Time: 16:01
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page session="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="vocabulary" tagdir="/WEB-INF/tags" %>

<vocabulary:layout pageName="allWordLists">
    <%--    List JSP - Logged in user: <%= session.getAttribute("Email") %> <br>--%>

    <h2>All word lists</h2>
    <table id="wordLists" class="table table-striped">
        <thead>
        <tr>
            <th>Word Lists</th>
            <th></th>
            <th></th>
            <th align="right"><a href="create">Create</a></th>
        </tr>
        <tr>
            <th style="width: 200px;">Name</th>
            <th style="width: 100px;">Language 1</th>
            <th style="width: 100px;">Language 2</th>
            <th style="width: 250px;">Description</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${lists}" var="list">
            <tr>
                <td>
                    <spring:url value="/lists/add/{wordListId}.html" var="wordListUrl">
                        <spring:param name="wordListId" value="${list.id}"/>
                    </spring:url>
                    <a href="${fn:escapeXml(wordListUrl)}"><c:out value="${list.name}"/></a>
                </td>
                <td>${list.getLang1()}</td>
                <td>${list.getLang2()}</td>
                <td>${list.getDescription()}</td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
</vocabulary:layout>

src/main/webapp/WEB-INF/views/create.jsp
<%--
  Created by IntelliJ IDEA.
  User: Honza
  Date: 07.01.2020
  Time: 17:04
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page session="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="vocabulary" tagdir="/WEB-INF/tags" %>

<vocabulary:layout pageName="createWordList">

    <div class="container">
        <h2>Create new word list</h2>
        <form:form id="create-form" modelAttribute="wordListForm" action="/create" method="post" role="form">
            <div class="form-group">
                <label>Name</label>
                <input autocomplete="off" type="text" name="name" id="name" class="form-control">
                <label>Description</label>
                <input autocomplete="off" type="text" name="description" id="description" class="form-control">
                <br>
                <label>Language 1</label>
                <select name="iso1" id="iso1">
                    <c:forEach items="${languages}" var="lang">
                        <option value="${lang.getIso()}">${lang.getName()}</option>
                    </c:forEach>
                </select>
                <label>Language 2</label>
                <select name="iso2" id="iso2">
                    <c:forEach items="${languages}" var="lang">
                        <option value="${lang.getIso()}">${lang.getName()}</option>
                    </c:forEach>
                </select>
                <br>
                <br>
                <c:set var="formHasRegisterError">
                    <form:errors/>
                </c:set>
                <c:if test="${not empty formHasRegisterError}">
                    <div class="alert alert-danger">
                        <i class="fa fa-ban"></i>&nbsp;${formHasRegisterError}
                    </div>
                </c:if>
                <button type="submit" class="btn btn-default">Create</button>
            </div>

        </form:form>


    </div>

</vocabulary:layout>

src/main/webapp/WEB-INF/views/head.jsp
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />

<%--<!-- jQuery -->--%>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<%--<!-- Bootstrap CSS -->--%>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://getbootstrap.com/docs/3.3/examples/dashboard/dashboard.css">

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<!-- Font-awesome -->
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
	integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
	crossorigin="anonymous">

src/main/webapp/WEB-INF/views/statisticsAfterPractice.jsp
<%--
  Created by IntelliJ IDEA.
  User: michalcerny
  Date: 23/12/2019
  Time: 17:34
  To change this template use File | Settings | File Templates.
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page session="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="vocabulary" tagdir="/WEB-INF/tags" %>

<vocabulary:layout pageName="statisticsAfterPractice">

    <h2>Statistics</h2>
    <table id="usersLists" class="table table-striped">
        <thead>
        <tr>
            <th style="width: 200px;">Language 1</th>
            <th style="width: 200px;">Language 2</th>
            <th>Score</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${words}" var="word">
            <tr>
                <td>${word.wordForTranslation.spelling}</td>
                <td>${word.wordTranslated.spelling}</td>
                <td>${word.score}</td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
    <a href="/" class="btn btn-default">Finish</a>

</vocabulary:layout>